// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }











import type { Metadata } from "next";
import { Teko, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";

const teko = Teko({
  variable: "--font-teko",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title:
    "Ayan Sujon - Full Stack Developer, MERN Stack Developer, React Developer, Node.js Developer",
  description:
    "Ayan Sujon is a skilled Full Stack Developer specializing in MERN Stack, React, and Node.js development. With a passion for creating dynamic web applications, Ayan combines expertise in both frontend and backend technologies to deliver seamless user experiences. Whether it's building responsive interfaces or designing robust server-side solutions, Ayan is dedicated to crafting efficient and scalable applications that meet the needs of modern users.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${teko.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>
        <Navbar/>
        {children}
        </div>
      </body>
    </html>
  );
}

